name: Tags

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'deploy skip') "
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo lets create a tag!