name: Tags

on:
  pull_request:
    branches: [ develop ]
    types: [ closed ] 

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'release' }}
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!